/**
 * CIQUAL (ANSES) food composition table → eu_foods rows. Reads the CSV that Excel or LibreOffice
 * saves from the official "Table Ciqual" spreadsheet (any of ; , or tab as separator, decimal
 * commas, values like "< 0,5", "traces" or "-"). Pure, so it's unit-tested.
 */

export interface EuFoodRow {
  source: 'ciqual';
  code: string;
  name_en: string;
  name_local: string | null;
  local_lang: 'fr';
  kcal: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  fiber_g: number;
}

/** Splits CSV text into rows of cells (quotes, doubled quotes and newlines inside quotes). */
export function parseCsv(text: string): string[][] {
  const clean = text.replace(/^﻿/, '');
  const firstLine = clean.slice(0, clean.indexOf('\n') === -1 ? undefined : clean.indexOf('\n'));
  const sep = [';', '\t', ','].sort(
    (a, b) => firstLine.split(b).length - firstLine.split(a).length,
  )[0]!;
  const rows: string[][] = [];
  let row: string[] = [];
  let cell = '';
  let quoted = false;
  for (let i = 0; i < clean.length; i++) {
    const c = clean[i]!;
    if (quoted) {
      if (c === '"' && clean[i + 1] === '"') {
        cell += '"';
        i++;
      } else if (c === '"') quoted = false;
      else cell += c;
    } else if (c === '"') quoted = true;
    else if (c === sep) {
      row.push(cell);
      cell = '';
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && clean[i + 1] === '\n') i++;
      row.push(cell);
      if (row.some((x) => x.trim() !== '')) rows.push(row);
      row = [];
      cell = '';
    } else cell += c;
  }
  row.push(cell);
  if (row.some((x) => x.trim() !== '')) rows.push(row);
  return rows;
}

/** "12,5" → 12.5; "< 0,5" → 0.25 (half the limit); "traces", "-", "" → 0; nonsense → null. */
export function ciqualNumber(raw: string | undefined): number | null {
  const v = (raw ?? '').trim().replace(',', '.');
  if (v === '' || v === '-' || /^traces?$/i.test(v)) return 0;
  const lt = /^<\s*([\d.]+)$/.exec(v);
  if (lt) return Number(lt[1]) / 2;
  const n = Number(v);
  return Number.isFinite(n) && n >= 0 ? n : null;
}

const COLUMNS: Record<keyof Omit<EuFoodRow, 'source' | 'local_lang'>, RegExp[]> = {
  code: [/^alim_code$/i],
  name_en: [/^alim_nom_eng?$/i, /^alim_nom_en/i],
  name_local: [/^alim_nom_fr$/i],
  // The EU regulation energy value (what labels use), else any kcal column.
  kcal: [/regulation.*kcal\/100\s?g/i, /kcal\/100\s?g/i],
  protein_g: [/^prot[ée]in.*\(g\/100\s?g\)/i],
  carbs_g: [/^(carbohydrate|glucides)\s*\(g\/100\s?g\)/i, /^carbohydrate/i],
  fat_g: [/^(fat|lipides)\s*\(g\/100\s?g\)/i, /^fat\b/i],
  fiber_g: [/^(fibres?|fibers?)/i],
};

export function columnIndexes(header: string[]): Record<keyof typeof COLUMNS, number> {
  const out = {} as Record<keyof typeof COLUMNS, number>;
  for (const [key, patterns] of Object.entries(COLUMNS) as [keyof typeof COLUMNS, RegExp[]][]) {
    let index = -1;
    for (const p of patterns) {
      index = header.findIndex((h) => p.test(h.trim()));
      if (index !== -1) break;
    }
    if (index === -1 && key !== 'name_local' && key !== 'fiber_g') {
      throw new Error(`CIQUAL column not found: ${key}`);
    }
    out[key] = index;
  }
  return out;
}

/** The rows that can be used: a code, an English name and a plausible energy value. */
export function ciqualRows(csv: string): { rows: EuFoodRow[]; skipped: number } {
  const [header, ...data] = parseCsv(csv);
  if (!header) return { rows: [], skipped: 0 };
  const col = columnIndexes(header);
  const rows: EuFoodRow[] = [];
  let skipped = 0;
  for (const r of data) {
    const code = r[col.code]?.trim() ?? '';
    const name = r[col.name_en]?.trim() ?? '';
    const kcal = ciqualNumber(r[col.kcal]);
    const n = (key: 'protein_g' | 'carbs_g' | 'fat_g' | 'fiber_g') =>
      col[key] === -1 ? 0 : Math.min(100, ciqualNumber(r[col[key]]) ?? 0);
    if (!code || !name || kcal === null || kcal > 950) {
      skipped++;
      continue;
    }
    const local = col.name_local === -1 ? '' : (r[col.name_local]?.trim() ?? '');
    rows.push({
      source: 'ciqual',
      code: code.slice(0, 40),
      name_en: name.slice(0, 300),
      name_local: local ? local.slice(0, 300) : null,
      local_lang: 'fr',
      kcal: Math.round(kcal * 100) / 100,
      protein_g: n('protein_g'),
      carbs_g: n('carbs_g'),
      fat_g: n('fat_g'),
      fiber_g: n('fiber_g'),
    });
  }
  return { rows, skipped };
}

const sqlText = (v: string | null) => (v === null ? 'null' : `'${v.replace(/'/g, "''")}'`);

/** Upserts as SQL (for the SQL editor or psql), in chunks. */
export function toSql(rows: EuFoodRow[], chunk = 500): string {
  const parts: string[] = [
    '-- CIQUAL (ANSES), Licence Ouverte / Etalab 2.0. Generated by scripts/foods/import-ciqual.mjs.',
  ];
  for (let i = 0; i < rows.length; i += chunk) {
    const values = rows
      .slice(i, i + chunk)
      .map(
        (r) =>
          `(${sqlText(r.source)}, ${sqlText(r.code)}, ${sqlText(r.name_en)}, ${sqlText(r.name_local)}, ${sqlText(r.local_lang)}, ${r.kcal}, ${r.protein_g}, ${r.carbs_g}, ${r.fat_g}, ${r.fiber_g})`,
      )
      .join(',\n  ');
    parts.push(`insert into public.eu_foods (source, code, name_en, name_local, local_lang, kcal, protein_g, carbs_g, fat_g, fiber_g) values
  ${values}
on conflict (source, code) do update set name_en = excluded.name_en, name_local = excluded.name_local,
  kcal = excluded.kcal, protein_g = excluded.protein_g, carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g, fiber_g = excluded.fiber_g;`);
  }
  return parts.join('\n\n') + '\n';
}
